### ISSUE TITLE
mp3_decoder.py import bug

### ISSUE THREAD

**Issue by maxl28** [maxammann/glados#1]
It seems that python is unable to find 'distutils.spawn' if only 'distutils' was imported, resulting in the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/glados-run", line 4, in <module>
    __import__('pkg_resources').run_script('glados==0.1', 'glados-run')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/glados-0.1-py2.7.egg/EGG-INFO/scripts/glados-run", line 2, in <module>
    from glados import main
  File "/usr/local/lib/python2.7/dist-packages/glados-0.1-py2.7.egg/glados/main.py", line 12, in <module>
    from glados.audio.playback import Playback
  File "/usr/local/lib/python2.7/dist-packages/glados-0.1-py2.7.egg/glados/audio/playback.py", line 8, in <module>
    from glados.audio.mp3_decoder import mp3_decode
  File "/usr/local/lib/python2.7/dist-packages/glados-0.1-py2.7.egg/glados/audio/mp3_decoder.py", line 24, in <module>
    decoder = find_decoder()
  File "/usr/local/lib/python2.7/dist-packages/glados-0.1-py2.7.egg/glados/audio/mp3_decoder.py", line 9, in find_decoder
    lame = distutils.spawn.find_executable("lame")
AttributeError: 'module' object has no attribute 'spawn'`

A fix would be to change 'glados/glados/audio/mp3_decoder.py':

replace 'import distutils' with 'from distutils import spawn' and change the two lines which use this module accordingly.

**Comment by maxammann** [comment]
Haven't thought anybody would run this :D Worked last year on it, but I think I wasn't really able to get the passive voice recognition good enough, used julius back then

Google voice recognition is just soo superior, but I don't want google to listen constantly to me.
